### ISSUE TITLE
Android app crashed on simulator

### ISSUE THREAD

**Issue by rahulmishra1991** [prscX/react-native-voice-recorder#24]
When i am clicking on my onrecord function app is crashing on my simulator. It's working on my testing device but not working on the some other devices.

_onRecord = async (idx, relation) => {
    const token = await AsyncStorage.getItem('access_token');

    this.props.setLoader(true);

    RNVoiceRecorder.Record({
      onDone: (path) => {
        console.log("PATH",path);

        const imgUri = Platform.OS === 'android' ? 'file://' + path : path;
        const templateId = this.props.navigation.getParam('templateId', 0);
        const documentId = this.props.navigation.getParam('documentId', 0);
        recordingPath = imgUri;
        Alert.alert(
          'Are you sure you want to use this declaration?',
          '',
          [
            {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
            {
              text: 'OK', onPress: () => {
                console.log("templateId >> "+templateId);
                console.log("relation >> "+relation);
                RNFetchBlob.fetch('POST', API_PATHS.AUDIO_RECORDING, {
                  Authorization : "Bearer "+token,
                  'Content-Type' : 'multipart/form-data',
                }, [

                  { name : 'file_input', filename : 'dotcom_recorded_audio.wav', type:'audio/wav', data: RNFetchBlob.wrap(imgUri)},
                  {name: 'documentId', data: documentId.toString()},
                  {name: 'relation', data: relation}
                ]).then((resp) => {
                  let response = resp.json();
                  console.log("response.data => ",response.status);
                  if (response.success) {
                    recordingPath = '';
                    this.state.audioRecordings[idx].file = response.data;
                    this.state.audioRecordings[idx].fileValidate = true;
                    this.handler('success','Success',response.message);

                    this.props.setLoader(false);
                    console.log("this.state.audioRecordings",this.state.audioRecordings);
                  }else{
                    this.props.setLoader(false);
                  }
                }).catch((err) => {
                  console.log("ERROR",err);
                  this.handler('error','Error',err.message);
                  this.props.setLoader(false);
                })

              }
            },
          ],
          { cancelable: false }
        )
      },
      onCancel: () => {
        this.props.setLoader(false);
        console.log("Mood sahi nhi hai");
      }
    })
  }

**Comment by Fabrice-Beya** [comment]
Seeing the same issue this is extract from logcat:

2020-09-13 07:51:27.646 6614-6614/com.mayelelabs.augani D/AndroidRuntime: Shutting down VM
2020-09-13 07:51:27.647 6614-6614/com.mayelelabs.augani E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mayelelabs.augani, PID: 6614
    com.facebook.react.bridge.NoSuchKeyException: path
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:123)
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:127)
        at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:162)
        at px.voicerecorder.RNVoiceRecorderModule$2.onPermissionsChecked(RNVoiceRecorderModule.java:105)
        at com.karumi.dexter.DexterInstance$1.run(Unknown Source:43)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by Fabrice-Beya** [comment]
I resolved it by checking the path, turns out the path I was passing was not correct.
